# Generated by Django 2.2 on 2021-12-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BukuCoeg',
            new_name='Ebook',
        ),
        migrations.RenameModel(
            old_name='Penilaeun',
            new_name='Review',
        ),
    ]
